# Configuration file for _updateModules.R
# This file defines module settings, file mappings, and deployment parameters

# Global settings
global:
  new_version: "0.0.3.45"
  new_date: "2025-07-06"
  base_repo_dir: "/Users/serdarbalci/Documents/GitHub/ClinicoPathJamoviModule"

# Operation modes
modes:
  quick: false
  check: false
  extended: false
  webpage: false
  commit_modules: false
  WIP: false

# Required packages for validation
required_packages:
  - xfun
  - fs
  - jmvtools
  - devtools
  - purrr
  - digest
  - yaml
  - future

# Module definitions
modules:
  jjstatsplot:
    enabled: false
    directory: "/Users/serdarbalci/Documents/GitHub/jjstatsplot"
    menuGroup_pattern: "menuGroup: JJStatsPlot$"
    menuGroup_pattern_wip: "menuGroup: JJStatsPlot"

    data_files:
      - "histopathology.rda"
      - "groupsummary_financial_data.rda"
      - "groupsummary_simple.rda"
      - "categorical_quality_data.rda"
      - "hullplot_clinical_data.rda"
      - "hullplot_customer_data.rda"
      - "hullplot_experimental_data.rda"
      - "hullplot_quality_data.rda"
      - "hullplot_survey_data.rda"
      - "jggstats_clinical_data.rda"
      - "jggstats_educational_data.rda"
      - "jggstats_experimental_data.rda"
      - "jggstats_financial_data.rda"
      - "jggstats_marketing_data.rda"
      - "jggstats_medical_data.rda"
      - "jggstats_pharmaceutical_data.rda"
      - "jggstats_psychological_data.rda"
      - "jggstats_quality_data.rda"
      - "jggstats_survey_data.rda"

    r_files: []

    vignette_files:
      - "jjstatsplot-introduction.Rmd"
      - "correlations-scatterplots.Rmd"
      - "continuous-comparisons.Rmd"
      - "categorical-plots.Rmd"
      - "use-jjstatsplot-in-R.Rmd"
      - "jjstatsplot-03-continuous-comparisons.Rmd"
      - "jjstatsplot-10-correlations-scatterplots-legacy.Rmd"
      - "jjstatsplot-22-jggsankeyfier-comprehensive.qmd"
      - "jjstatsplot-23-jggstats-comprehensive.qmd"

    test_files: []

    required_directories:
      - "data"
      - "R"
      - "vignettes"
      - "jamovi"

  meddecide:
    enabled: false
    directory: "/Users/serdarbalci/Documents/GitHub/meddecide"
    menuGroup_pattern: "menuGroup: meddecide$"
    menuGroup_pattern_wip: "menuGroup: meddecide"

    data_files:
      - "histopathology.rda"
      - "roc_analysis_test_data.RData"
      - "cancer_biomarker_data.csv"
      - "cardiac_troponin_data.csv"
      - "sepsis_biomarker_data.csv"
      - "thyroid_function_data.csv"
      - "bayesdca_test_data.rda"
      - "breast_cancer_data.rda"
      - "breast_diagnostic_styles.rda"
      - "lymphoma_diagnostic_styles.rda"
      - "dca_test_data.csv"
      - "thyroid_function_data.rda"

    r_files:
      - "psychopdaroc_utilities.R"
      - "nomogrammer.R"
      - "meddecide-utils.R"
      - "meddecide_stats_utils.R"
      - "diagnostic_metrics.R"

    vignette_files:
      - "nogoldstandard.Rmd"
      - "diagnostic-tests.Rmd"
      - "decisionpanel_advanced.Rmd"
      - "decisionpanel_optimisation.Rmd"
      - "decisionpanel_clinical.Rmd"
      - "meddecide-vignettes.Rmd"
      - "medical_decision_tree_guide.Rmd"
      - "meddecide-03-roc-analysis.Rmd"
      - "meddecide-03-agreement-analysis.Rmd"
      - "meddecide-25-diagnostic-tests-legacy.Rmd"
      - "meddecide-22-diagnostic-style-clustering-legacy.Rmd"
      - "meddecide-29-decision-tree-vs-markov-analysis-legacy.Rmd"
      - "meddecide-20-decisionpanel-clinical-legacy.Rmd"

    test_files:
      - "test-decision.R"
      - "test-roc.R"

    required_directories:
      - "data"
      - "R"
      - "vignettes"
      - "jamovi"
      - "tests/testthat"

  jsurvival:
    enabled: true
    directory: "/Users/serdarbalci/Documents/GitHub/jsurvival"
    menuGroup_pattern: "menuGroup: Survival$"
    menuGroup_pattern_wip: "menuGroup: Survival"

    data_files:
      - "histopathology.rda"
      - "melanoma.rda"
      - "data_longitudinal.rda"

    r_files: []

    vignette_files:
      - "jsurvival.Rmd"
      - "jsurvival-14-comparing-survival.Rmd"
      - "jsurvival-04-stage-migration-analysis.Rmd"
      - "jsurvival-15-competing-survival.Rmd"
      - "jsurvival-08-stage-migration-analysis-legacy.Rmd"

    test_files: []

    required_directories:
      - "data"
      - "R"
      - "vignettes"
      - "jamovi"

  ClinicoPathDescriptives:
    enabled: false
    directory: "/Users/serdarbalci/Documents/GitHub/ClinicoPathDescriptives"
    menuGroup_pattern: "menuGroup: Exploration$"
    menuGroup_pattern_wip: "menuGroup: Exploration"

    data_files:
      - "histopathology.rda"
      - "histopathologyDescriptives.omv"
      - "treatmentResponse.omv"
      - "treatmentResponse.rda"
      - "multi_group_workflow.rda"
      - "colorectal_ihc_data.csv"
      - "sarcoma_ihc_data.rda"
      - "raw_with_time.rda"
      - "ggflowchart_comprehensive_data.rda"
      - "ihc_test_data.rda"
      - "percent_no_time.csv"
      - "election_survey_data.rda"

    r_files: []

    vignette_files:
      - "data-summary.Rmd"
      - "visualization.Rmd"
      - "clinicopath-descriptives-23-hullplot-comprehensive.qmd"
      - "clinicopath-descriptives-17-desctools.qmd"
      - "clinicopath-descriptives-04-benford.qmd"
      - "clinicopath-descriptives-13-function-summarydata.Rmd"

    test_files: []

    required_directories:
      - "data"
      - "R"
      - "vignettes"
      - "jamovi"

# File extensions to copy for jamovi modules

jamovi_extensions:
  - ".b.R"
  - ".a.yaml"
  - ".r.yaml"
  - ".u.yaml"

# Security settings
security:
  validate_paths: true
  verify_checksums: true
  max_file_size_mb: 100

# Performance settings
performance:
  parallel_processing: false
  max_workers: 4
  incremental_updates: true

# Backup settings
backup:
  enabled: true
  retention_days: 30
  backup_location: "backups"
